### ISSUE TITLE
[Feature Request] Validierungsergebnis in eine Textdatei speichern

### ISSUE THREAD

**Issue by demsul** [gematik/app-referencevalidator#10]
Eine Verbesserung wäre ein zusätzlicher Parameter um das Ergebnis bzw. die komplette Ausgabe zusätzlich in eine Datei zu speichern like --txt-output [Dateipfad]. So hätte man unter anderem die Möglichkeit das Ergebnis zu parsen.
Wünschenswert wäre zu dem ein entsprechender Exitcode bei einer fehlerhaften/erfolgreichen Validierung. Aktuell wird soweit ich das beurteilen konnte immer 0 zurückgegeben.

**Comment by alexey-tschudnowsky** [comment]
Hallo @demsul ,
danke für den Vorschlag. Eine Frage zum besseren Verständnis: Haben Sie schon Erfahrungen mit der Umleitung der Ausgabe des Validators mit Betriebssystemmitteln gesammelt, z.B.: 
`java -jar .\referencevalidator-cli-1.1.0.jar eau .\eingabe.xml > output.txt`? Inwiefern würde sich die angefragte Funktionalität unterscheiden?

Die Verwendung von exit/eror codes der Anwendung um die Fachergebnisse statt Ausnahmesituationen zu kommunizieren halte ich für wenig geeignet. Die Bewertung einer Instanz als invalide (nicht-Profil-konform) ist ein durchaus erwartetes Ergebnis eines ordnungsgemäßen Durchlaufs des Programms. Ordnungsgemäße Durchläufe erwartet man allerdings mit einem Exit Code 0 und keinem Error Code. Error Codes deuten ja auf einen Abbruch / Ausnahmesituation hin und können vom Betriebssystem / Werkzeugen entsprechend unerwartet behandelt werden. 

Es gibt ansonsten bereits ein ähnliches Feature Request unter Issue #6 (Ausgabe als OperationOutcome) - würde diese Art der Ausgabe Ihr Szenario auch lösen?

**Comment by demsul** [comment]
Im Moment leiten wir den stdout/stderr, wie Sie es angegeben haben, in eine Datei um. Zur Not reicht das aus. Wenn man aber die Ausgabe zusätzlich noch in der Konsole (im Fenster) sehen möchte, dann geht das mit der Umleitung nicht mehr.

Um das Ergebnis zu bewerten gehen wir den Inhalt der umgeleiteten Ausgabe durch und suchen akt. nach "Valid: true" oder "Valid: false".

**Comment by DarthGizka** [comment]
Ausgabe als OperationOutcome würde auch detaillierte Analysen der Meldungen auf einfache Weise ermöglichen, aufgrund der standardisierten Struktur und weil die Message-Ids eine präzise Klassifikation auch ohne Regex-Voodoo erlauben. Last but not least könnte die gleiche Analyselogik auch unverändert auf die Ausgaben anderer Validatoren angewendet werden, sofern diese ebenfalls ein OperationOutcome ausspucken (wie z.B. der [offizielle HL7-Validator](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator)). Das könnte u.a. bei der Qualitätssicherung für den Referenzvalidator selbst von Vorteil sein.

**Comment by alexey-tschudnowsky** [comment]
Hallo @demsul, 
in der frisch veröffentlichten [Version 2.2.0 vom Referenzvalidator](https://github.com/gematik/app-referencevalidator/releases/tag/2.2.0) ist der Kommandozeilenparameter `--output OUTPUT_FILE_NAME` enthalten, mit dem das Schreiben des Validierungsergebnisses in eine Ausgabedatei nun möglich ist. Geschrieben wird eine OperationOutcome (siehe [Strukturdefinitionen](https://github.com/gematik/app-referencevalidator/tree/main/docs/profiles/fsh/fsh-generated/resources)).
