### ISSUE TITLE
OutOfMemory-Exception bei Einsatz unter Dauerlast

### ISSUE THREAD

**Issue by bneidhold** [gematik/app-referencevalidator#11]
Der Validator ist bei uns auf einer Maschine mit >10GB RAM und 4 Cores im Einsatz. Es werden mehrere 100.000 Rezepte (Verordnungen +Abgabedaten) pro Tag damit validiert - teilweise auch parallel.
Nach 3-7 Tagen gibt es OutOfMemory-Exceptions. Dies ist mehrfach genau so passiert. Beim ABDA-Referenzvalidator ist das Problem über Monate nicht aufgetreten.

**Comment by alexey-tschudnowsky** [comment]
Hallo @bneidhold ,
ich nehme an, der Referenzvalidator wird als Bibliothek in einem (Web) Service eingebunden? Wird eine einzige Instanz für alle eingehenden Requests verwendet oder mehrere? Gab es Beobachtungen wie der Speicherverbrauch über die Tage sich entwickelt (konstanter Anstieg vs sporadische Spitzen) und ob die Exceptions auf bestimmte 
 Ereignisse zurückzuführen sind (Lastspitzen, große TA7-Dateien etc.)?

**Comment by bneidhold** [comment]
Ja wir reden über einen Webservice. Es wird intern eine Instanz verwendet. 
Der Speicher schwingt im Normalbereich hin und her. Erst "kurz 1h" vor dem OOM geht es nach oben. Es werden keine TA7 damit validiert. Aber ja es passiert vermeintlich, wenn über längere Zeit parallel viel Last auf dem System ist.

**Comment by hattenbach** [comment]
lässt sich das provozierend nachstellen? können Vermutungen zu Auslösern aufgestellt werden?

**Comment by bneidhold** [comment]
ich bin mit Alexey im Chataustausch. Meine Vermutung ist, dass parallele Hochlast auf die eine Instanz des Validators der Auslöser sein kann. Wichtig war mir hier vor allem, das Verhalten einmal zu dokumentieren. Ich selbst versuche mit unterschiedlichen Ansätzen bei der Infrastruktur das Problem gerade in den Griff zu bekommen, OHNE dass ich den Java-Code selber anfasse.

**Comment by bneidhold** [comment]
Zwischenmeldung: nachdem wir vor 12 Wochen den maximalen Speicher auf 10GB! gesetzt haben, läuft der Service bisher stabil unter größerer paralleler Last.

**Comment by sebastian-arz** [comment]
Wir (ARZ Haan) haben dieses Problem auch.

Bei uns läuft der Referenzvalidator in einer Docker Umgebung mit 3 Replikas die je 2,5 GB RAM haben.

Nach einer gewissen Laufzeit (mehrmals täglich) stürzt der Referenzvalidator ab. 2,5 GB RAM für einen Pod in Kubernetes zu veranschlagen ist schon ziemlich viel.

Nach einem Neustart läuft der Validator erst mal eine gewisse Zeit stabil, was für uns nicht nach einem klassischen Last Problem aussieht.

Wiederholendes Muster ist, dass der Validator nach einigen Stunden aussteigt. Wir behelfen uns aktuell mit einem Cronjob der die Pods nach 3 Stunden rotierend Neu startet, was aber schmerzlich ist denn die ersten Request nach Neustart sind echt extrem langsam, und wir nehmen aktuell eRezepte im 2 stelligen Millionenbereich / Monat an.

**Comment by alexey-tschudnowsky** [comment]
Hallo @sebastian-arz ,
danke für die Meldung. Das Problem konnten wir schon eingrenzen (liegt an einem Bug in der zugrundeliegenden HL7 Validator Engine https://github.com/hapifhir/org.hl7.fhir.core/issues/1412) und werden eine erste Abhilfe im Rahmen des BugFix-Releases 2.0.2 bereitstellen. Weitere Maßnahmen sind schon geplant. Ich würde mich freuen, wenn Sie das Release zeitnah nach Erscheinen in Ihrer Umgebung ausprobieren und die Aussage über die Wirksamkeit treffen könnten. 

@bneidhold

**Comment by bneidhold** [comment]
Da wir den Fehler faktisch mehrfach täglich haben und damit gut nachstellen können, teste ich natürlich gern zeitnah neue Versionen dagegen

**Comment by alexey-tschudnowsky** [comment]
das neue Release ist nun verfügbar https://github.com/gematik/app-referencevalidator/releases/tag/2.0.2

**Comment by sebastian-arz** [comment]
Hallo @alexey-tschudnowsky,

wir freuen uns Ihnen mitteilen zu können, dass ihre neue Version bei uns gut funktioniert, und wir seit der Nutzung (Montag Nachmittag) keine weiteren Memoryleaks feststellen konnten.

Für die gute und schnelle Hilfe bedanken wir uns

**Comment by alexey-tschudnowsky** [comment]
Hallo @sebastian-arz ,
danke für die Rückmeldung und ich hoffe, dass der Betrieb auch weiterhin stabil bleibt.
Viele Grüße
Alexey Tschudnowsky

**Comment by alexey-tschudnowsky** [comment]
Die Korrektur erfolgte im [Release 2.0.2](https://github.com/gematik/app-referencevalidator/releases/tag/2.0.2). Solange es keine weiteren Auffälligkeiten gibt, schließen wir den Vorgang. Danke an alle Beteiligten für die Unterstützung bei der Problemanalyse.
