### ISSUE TITLE
Korrekturrelease Version 1.3.2

### ISSUE THREAD

**Issue by scanacs-agruhn** [gematik/app-referencevalidator#17]
> Das Korrekturrelease Version 1.3.2 darf ab dem 01.06.2024 verwendet werden.
> Download des Korrekturreleases: https://simplifier.net/packages/de.gkvsv.erezeptabrechnungsdaten/1.3.2

https://simplifier.net/erezeptabrechnungsdaten

When did you plan to integrate this package as dependency. Currently we cannot test the new specification!

**Comment by alexey-tschudnowsky** [comment]
Hello @scanacs-agruhn ,

the new version of the validator with the 1.3.2 package will be published within the next days. We apologize for the delay.

Best Regards,
Alexey Tschudnowsky

**Comment by alexey-tschudnowsky** [comment]
Die Änderung wurde mit https://github.com/gematik/app-referencevalidator/releases/tag/2.3.0 umgesetzt
