### ISSUE TITLE
Falscher code für https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_KBV_DMP wird in Validator-Version 2.4.0 nicht mehr erkannt

### ISSUE THREAD

**Issue by joergreichert** [gematik/app-referencevalidator#22]
Bei uns werden die Gematik eRezept-Examples regelmäßig gegen den Referenzvalidator getestet

Bei der Version 2.3.0 wurden bei den beiden Negativ-Testfällen 
 * https://github.com/gematik/eRezept-Examples/blob/main/Negative-Examples/2_01.07.2023/KBV_PR_ERP_Bundle/e98da709-d9f8-494d-87b0-a59a0f471924_01.xml
 * https://github.com/gematik/eRezept-Examples/blob/main/Negative-Examples/2_01.07.2023/KBV_PR_ERP_Bundle/e98da709-d9f8-494d-87b0-a59a0f471924_03.xml

jeweils der falsche DMP Code gefunden:

```
SingleValidationMessage[col=29,row=404,locationString=Bundle.entry[5].resource/*Coverage/18eba2db-eac4-4f78-bd0a-b061b8f35d95*/.extension[1].value.ofType(Coding),message=Unknown code 'https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_KBV_DMP#42' for 'https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_KBV_DMP#42',Terminology_PassThrough_TX_Message,severity=error]
```

Seit dem Upgrade von 

```
        <hapi-fhir.version>7.2.0</hapi-fhir.version>
        <gematik-reference-validator.version>2.3.0</gematik-reference-validator.version>

       ...

        <dependency>
            <groupId>de.gematik.refv</groupId>
            <artifactId>referencevalidator-lib</artifactId>
            <version>${gematik-reference-validator.version}</version>
        </dependency>
```

auf 

```
        <hapi-fhir.version>7.2.2</hapi-fhir.version>
        <gematik-reference-validator.version>2.4.0</gematik-reference-validator.version>
```

werden diese nicht mehr gefunden.

**Comment by alexey-tschudnowsky** [comment]
Hallo @joergreichert ,
kann es sein, dass die Validierung ohne Profilgültigkeitszeitraumprüfung aufgerufen wird - also mit 
`options.setProfileValidityPeriodCheckStrategy(ProfileValidityPeriodCheckStrategy.IGNORE);`? Wenn man nämlich Profilgültigkeitsprüfung abschaltet, dann spielen auch Datumsangaben keine Rolle mehr und es werden aktuellste Packages und Schlüsseltabellen verwendet, die das angegebene DMP-Kennzeichen bereits enthalten. In der Version 2.4.0 des Validators kamen ja neue Packages und neue Schlüsseltabellen (einschließlich neue DMP-Kennzeichen dazu). 

Die beiden referenzierten Instanzen weisen das Erstellungsdatum (`authoredOn`) 2023-05-23 auf - zu dem Zeitpunkt waren die referenzierten Profile `KBV_PR_ERP_Bundle|1.1.0` noch gar nicht gültig, sondern erst seit dem 2023-07-01. Zu diesem Zeitpunkt 
 gibt es also noch keine "gültigen" Packages, sodass jede weitere Validierung abbrechen müsste. Das entdeckt der Validator auch, wenn er ohne Parametrisierung gestartet wird (im Folgenden aus der Konsole heraus):

```
PS C:\Dev\gematik-referenzvalidator Releases\2.4.0> java -jar .\referencevalidator-cli-2.4.0.jar erp .\e98da709-d9f8-494d-87b0-a59a0f471924_01.xml
14.08.24-09:50:49.448 INFO  -
gematik Referencevalidator 2.4.0
Java:   17.0.11 from C:\Program Files\Eclipse Adoptium\jdk-17.0.11.9-hotspot on amd64 (64bit). 8136MB, 16 CPU cores available
Locale: en_US

14.08.24-09:50:49.755 INFO  - Reading input file .\e98da709-d9f8-494d-87b0-a59a0f471924_01.xml...
14.08.24-09:50:49.792 INFO  - Validating against https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Bundle|1.1.0...
14.08.24-09:50:51.476 INFO  -

=====  Valid: false =====

See 1 errors below.

      Severity     Code                                         Location (FHIRPath)    Profile, Element and Problem description
      --------     ----------------------------------------     -------------------    ----------------------------------------
  1   ERROR        REFV_PROFILE_OUTSIDE_OF_VALIDITY_PERIOD      null   Profile https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Bundle|1.1.0 is invalid for the creation date of the resource (2023-05-23); only valid from 2023-07-01
```

Wenn man in den Beispielinstanzen das `authoredOn`-Datum nun dem Gültigkeitszeitraum des Profils anpasst, also bspw. auf den Wert 2023-**07**-23 setzt, dann findet der Validator die zu dem Zeitpunkt gültigen Packages und entdeckt auch das problematische DMP-Kennzeichen 42, welches erst in Zukunft, also ab 1.10.2024, verwendet werden darf.

**Comment by joergreichert** [comment]
Ja, das stimmt, ich wollte die Ausgangs-Testdateien unverändert lassen und hatte entsprechend ProfileValidityPeriodCheckStrategy.IGNORE gesetzt. Ich kann aber bestätigen, dass, wenn das authoredOn-Datum auf nach 1.7.2023 gesetzt ist, die Validierung die Fehler (auch mit ProfileValidityPeriodCheckStrategy.VALIDATE gesetzt) findet. Werde der Gematik vorschlagen, die Testdateien mal richtig zu datieren. Vielen Dank für die schnelle Klärung.
