### ISSUE TITLE
Verhaltensänderung (ERP-Modul): beim Wechsel von v2.5.1 auf v2.6.0 neuerdings Info-Meldungen wg. 2 vermißter Snomed-Codes

### ISSUE THREAD

**Issue by DarthGizka** [gematik/app-referencevalidator#27]
Version 2.6.0 liefert Info-Meldungen wegen vermißter Snomed-Codes, die es in Version 2.5.1 noch nicht gab.

JSON-Dump eines Issues aus dem OperationOutcome ([Freitext-Verordnung_V1/FT_V1_MedicationDispense.xml][Beispiel]):
```json
{
  "severity" : "information",
  "code" : "processing",
  "details" : {
    "coding" : [ {
      "system" : "http://hl7.org/fhir/java-core-messageId",
      "code" : "Terminology_PassThrough_TX_Message"
    } ]
  },
  "diagnostics" : "Code system definition is missing for 'http://snomed.info/sct#763158003'",
  "location" : [ "MedicationDispense.contained[0]/*Medication/208929ac-7835-4c9f-9051-29055ecd3214*/.extension[1].value.ofType(CodeableConcept).coding[0]", "Line 26, Col 20" ]
}
```

Beim Test gegen das ABDA-Beispiel-Repo betrifft das die folgenden beiden Snomed-Codes:
* 763158003 'Medicinal Product' (79 Mal)
* 373873005:860781008=362943005 (8 Mal)

In beiden Fällen handelt es sich um in den Profilen vorgeschriebene Festwerte (Medikations-Kategorie).

Das Gesamturteil ändert sich nicht, da es sich um eine Info-Meldung handelt. Es stellt sich allerdings die Frage, ob diese Verhaltensänderung beabsichtigt war oder nicht, da sie in den Release-Notes nicht aufgeführt ist und es eigentlich auch keinen gesteigerten Grund für eine diesbezügliche Änderung des ERP-Moduls gab.

[Beispiel]: https://github.com/DAV-ABDA/eRezept-Beispiele/blob/2023-07-01/Freitext-Verordnung/Freitext-Verordnung_V1/FT_V1_MedicationDispense.xml

**Comment by alexey-tschudnowsky** [comment]
Danke für den Hinweis. Wie richtig angemerkt, gibt der Validator beim Vorkommen von SNOMED-CT-CodeSystem INFO-Meldungen raus. Die Gesamtbewertung ändert sich dadruch nicht. Die Release Notes hätten an dieser Stelle in der Tat ausführlicher sein können - nehmen wir zukünftig zur Kenntnis. 

Der Grund der neuen INFO-Meldungen ist der Folgende. 

Der Referenzvalidator gibt grundsätzlich INFO-Meldungen über die CodeSysteme aus, deren Codes nicht überprüft werden (können) - z.B. PZN oder ASK (siehe auch [Anzuwendende Konfiguration des E-Rezept-Moduls](https://github.com/gematik/app-referencevalidator/blob/main/docs/concept/concept.md#anzuwendende-validierungskonfiguration)).

Mit der Version 2.6.0 wurde das Package [de.gematik.erezept-workflow.r4 1.4.3](https://simplifier.net/packages/de.gematik.erezept-workflow.r4/1.4.3) in das E-Rezept-Modul integriert. Da die neuen [GEM_ERP_PR_Medication-Profile](https://simplifier.net/packages/de.gematik.erezept-workflow.r4/1.4.3/files/2550130) auf [ePA-Medication-Profilen](https://simplifier.net/packages/de.gematik.epa.medication/1.0.3/files/2539778) basieren, können dort SNOMED-CT-Codes zur Kodierung des Arzneimittels / Substanz vorkommen. Der Validator kann diese Codes nicht prüfen, sodass das SNOMED-CT-CodeSystem absichtlich zur Liste der nicht validierbaren CodeSysteme [hinzugefügt](https://github.com/gematik/app-referencevalidator/blob/4261594a4efbe3288c3de1b93184e3d2d2d3f8c4/valmodule-erp/src/main/resources/erp/config.yaml#L9) wurde (ohne die Aufnahme in die Liste werden SNOMED-CT-Codes von der darunterliegenden HL7 Java FHIR-Engine stillschweigend ignoriert). Als Folge der Aufnahme in diese Liste werden jetzt INFO-Meldungen überall dort produziert, wo SNOMED-CT als CodeSystem vorkommt. Die Aufnahme in die Liste der nicht validierbaren CodeSysteme hätte schon in Vergangenheit passieren sollen um auf die in der Meldung beschriebenen Vorkommnisse von SNOMED-CT hinzuweisen. 

P.S. Die Überprüfung von Codes in Code-Systemen erfolgt unabhängig von der eventuell im Anschluss folgenden ValueSet-Validierung. Falls auf ein Element ein ValueSet-Binding definiert ist - auch auf explizit aufgelistete SNOMED-CT-Werte - wird die Zugehörigkeit des Codes zum ValueSet vom Validator überprüft. Das Gleiche betrifft fixedValues.

**Comment by DarthGizka** [comment]
Alexey, vielen Dank für die aufschlußreiche Erklärung. Es handelt sich also um eine gewollte Änderung, welche die Behandlung von SNOMED angleicht an die Behandlung anderer Codesysteme wie PZN usw. Das ergibt Sinn. Ich bin sowieso immer für alles zu haben, was die Dinge einfacher macht. ;-)

*P.S.: Grund meiner Anfrage war der Umstand, daß beim Test der neuen Version gegen die gesammelten E-Rezept-Beispieldaten sowie gegen vorhandenen Rezeptbestand aus der Produktion **unerwartete** Abweichungen gegenüber der Ausgabe der Vorgängerversion aufgetreten sind. Im vorliegenden Fall war es einfach, die Ausgabe der neuen Version auf Vergleichbarkeit mit der Ausgabe der alten Version zu hacken (Entfernen der beiden SNOMED-Infomeldungen und Rekonstituieren der 'Alles OK'-Infomeldung, falls sonst nichts mehr übrig wäre). Dadurch war es möglich, die Ausgaben in Textform direkt zu vergleichen (JSON-Dump des OperationOutcome), was eine wesentlich stärkere Form der Ausgabegleichheit nachweist als nur das Vergleichen des Booleschen Gesamturteils. Nach dieser Anpassung hat der Validatorvergleich nach 3 Millionen (Stereo-)Validierungen nur ein halbes Dutzend erwartete Abweichungen ausgespuckt. Grund für letztere war die Änderung von Fehlermeldungstexten durch die Gültigkeitsverlängerung von Profilen.*

**Comment by alexey-tschudnowsky** [comment]
@DarthGizka danke für die ausführlichen Prüfungen!
