### ISSUE TITLE
Unterstützung für https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_PR_CloseOperation_Input|1.4 zum 15.1.25 fehlt

### ISSUE THREAD

**Issue by bneidhold** [gematik/app-referencevalidator#30]
wie hier beschrieben muss in Zukunft die Dispensierung am Fachdienst als GEM_ERP_PR_CloseOperation_Input übergeben werden:
https://github.com/gematik/api-erp/blob/master/docs/erp_eml-epa-notes.adoc

Da bisher auch alle Daten, die an und vom E-Rezeptfachdienst übergeben werden validiert werden konnten, sollte auch ein entsprechendes Parameters-Objekt validierbar sein!

**Comment by florianschoffke** [comment]
Hallo @bneidhold,

was genau meinst du mit "validierbar sein"?
Hier ist ein Beispiel, was validierbar ist: https://simplifier.net/erezept-workflow/resources-fsh-generated-resources-parameters-examplecloseinputparameters

Falls du die Validierungsfehler von "ref-1" in diesem Beispiel meinst: https://simplifier.net/erezept-workflow/fsh-generated-resources-parameters-examplecloseinputparameterskombipackung
Hier haben wir ein Bug Ticket bei Firely laufen. Der HAPI validiert korrekt, der Bug soll nach aktuellem Stand im November seitens Firely ausgerollt werden. Hierfür muss
1. Der Firely Validator gefixt und
2. Der neue Validator auf Simplifier verwendet werden.

Falls das nicht die richtige Antwort war, bitte gerne noch mal genauer erklären, danke.

**Comment by joergreichert** [comment]
```
de.gematik.refv.commons.exceptions.UnsupportedProfileException: Profile(s) https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_PR_PAR_CloseOperation_Input|1.4 unsupported

	at de.gematik.refv.commons.validation.GenericValidator.validate(GenericValidator.java:110)
	at de.gematik.refv.commons.validation.BaseValidationModule.validateString(BaseValidationModule.java:70)
```
wenn man in den ValidationOptions die profiles entsprechend setzt. Wenn man die Profile-Liste an den ValidationOptions nicht setzt, geht es aber durch. Getestet mit der Datei: API-Examples/2025-01-15/erp_abrufen/06_request_taskClose.xml

**Comment by florianschoffke** [comment]
Hallo @joergreichert,
Können Sie ihre Anmerkung/Frage noch etwas ausführen? Dann kann ich ggf. besser unterstützen.

**Comment by joergreichert** [comment]
Im Prinzip das gleiche Problem, das Benjamin beschrieben hat, wenn ich das neue Close-Eingabe validieren möchte und beim Referenz-Validator die Profile einschränke, dass das was ich reingebe auch wirklich eine Close-Eingabe mit entsprechenden Profil--Version ist (und nicht irgendein anderes Objekt, was vielleicht FHIR-valide ist, ich aber an der Stelle nicht erwartet), dann schlägt der Referenzvalidator fehl, weil wohl bei der Übergabe der Profile an den ValidationOptions scheinbar das 1.4 Close-Input-Profil noch nicht erkannt/unterstützt wird:

```
val expectedProfiles = listOf("https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_PR_PAR_CloseOperation_Input|1.4")
val validationOptions = ValidationOptions.getDefaults().apply {
   profileValidityPeriodCheckStrategy = ProfileValidityPeriodCheckStrategy.VALIDATE
   profiles = expectedProfiles
}
val validationResult = validator.validateString(
  Files.readString(Paths.get("API-Examples/2025-01-15/erp_abrufen/06_request_taskClose.xml")),
   validationOptions
)
```

Wenn ich das Setzen von profiles = expectedProfiles weglasse, geht die Validierung (aber dann könnte ich auch eine Prescription-Bundle reingeben, das valide wäre, obwohl ich an der Stelle, an der ich den Validator aufrufe, nur auf valide CloseOperation-Inputs prüfen möchte).

**Comment by alexey-tschudnowsky** [comment]
Hallo @joergreichert ,
ich glaube, es handelt sich um 2 verschiedene Issues:
1) @bneidhold  hat gemeldet, dass GEM_ERP_**PR**\_CloseOperation_Input nicht mehr unterstützt wird - das ist auch richtig so, weil stattdessen zukünftig GEM_ERP_PR\_**PAR**_CloseOperation_Input verwendet werden soll. Das verlinkte Beispiel war falsch und wurde zwischenzeitlich korrigiert. 
2) Sie meinen, dass auch GEM_ERP_PR__**PAR**_CloseOperation_Input|1.4 nicht validiert werden kann und zeigen ein Code-Beispiel. Hier kann ich das Problem leider lokal nicht reproduzieren und hätte gern etwas mehr Informationen von Ihnen:
- Welche Version vom Referenzvalidator ist im Einsatz? Das neue Profil GEM_ERP_PR_**PAR**_CloseOperation_Input|1.4 wird erst ab den  Versionen 2.6.* unterstützt
- Bitte probieren Sie die Validierung mit der Konsolenvariante des Referenzvalidators aus und fügen Sie das Ergebnis dem Issue bei:
`java -jar .\referencevalidator-cli-2.6.1.jar erp "PATH_TO_FILE\06_request_taskClose.xml" --profile "https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_PR_PAR_CloseOperation_Input|1.4"`

**Comment by joergreichert** [comment]
Hallo @alexey-tschudnowsky, hatte die Maven-Dependency eigentlich auf 2.6.1 angehoben gehabt, aber wahrscheînlich hatte ich vergessen, im IntelliJ das Maven-Projekt zu refreshen, so dass er da noch die alte Version vom Validator verwendet hat. Danke für die Hilfe.

**Comment by bneidhold** [comment]
für mich ist der Punkt auch erledigt, nachdem das Bsp angepasst ist, funktioniert die Validierung wie gewünscht
