### ISSUE TITLE
DAV-EX-ERP-Chargenbezeichnung > 16 --'Angabe der NOCTU SOK und ZusatzattributAbgabeNoctu nur in Verbindung.' Fehler

### ISSUE THREAD

**Issue by ITKOE** [gematik/app-referencevalidator#31]
Guten Tag,

im Validator ist die <extension url="http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Chargenbezeichnung auf 16-mal begrenzt. Wenn mehr als 16 Erweiterungen vorhanden sind, tritt folgender Fehler auf: Regel PR-NOCTU: 
'Angabe der NOCTU SOK und ZusatzattributAbgabeNoctu nur in Verbindung.' Fehler. 
Ich konnte keine Regel finden, die die DAV-EX-ERP-Chargenbezeichnung auf maximal 16 begrenzt.

Vielen Dank

**Comment by alexey-tschudnowsky** [comment]
Guten Tag @ITKOE ,
der Fehler deutet eher auf die Verletzung der Regel PR-NOCTU, die im Profil [dav_pr_base_abrechnungszeilen](https://simplifier.net/erezeptabgabedatenbasis/dav_pr_base_abrechnungszeilen) wie folgt definiert ist:

> PR-NOCTU: Angabe der NOCTU SOK und ZusatzattributAbgabeNoctu nur in Verbindung.
(extension('http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Zusatzattribute').extension('ZusatzattributAbgabeNoctu').exists() implies (chargeItemCodeableConcept.coding.system = 'http://TA1.abda.de' and chargeItemCodeableConcept.coding.code = '02567018')) and ((chargeItemCodeableConcept.coding.system = 'http://TA1.abda.de' and chargeItemCodeableConcept.coding.code = '02567018') implies extension('http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Zusatzattribute').extension('ZusatzattributAbgabeNoctu').exists())

Falls diese Regel in der Instanz, die Sie validiert haben, nicht verletzt sein sollte, bitten wir um die Bereitstellung von dieser (anonymisierten) Beispielinstanz, damit wir den Fehler bei uns reproduzieren können.

**Comment by timorosenblatt** [comment]
Wir haben denselben Fehler heute auf Kundenseite gesehen.
Weder Noctu Zusatzattribut noch Sonderkennzeichen sind in den Abgabedaten enthalten.

In unserem Fall sind 20 Chargen angegeben.

**Comment by timorosenblatt** [comment]
[Freitext-Verordnung_V1.zip](https://github.com/user-attachments/files/17833063/Freitext-Verordnung_V1.zip)

Im Zip sind Freitext 1 Beispiele.
....16.xml funktioniert noch mit 16 Chargen
....17.xml funktioniert mit 17 Chargen nicht mehr und liefert den Fehler

**Comment by alexey-tschudnowsky** [comment]
Hallo @timorosenblatt ,
im ZIP sind nur OperationOutcomes drin aber nicht die ursprünglichen Dateien. Für die Analyse benötigen wir die ursprünglichen ggf. anonymisierten Eingabedateien

**Comment by timorosenblatt** [comment]
[PZN-Verordnung_Nr_1.zip](https://github.com/user-attachments/files/17841740/PZN-Verordnung_Nr_1.zip)
Im Zip sind modifizierte PZN 1 DAV/ABDA Beispiele.
....16.xml funktioniert noch mit 16 Chargen
....17.xml funktioniert mit 17 Chargen nicht mehr und liefert den Noctu Fehler

@alexey-tschudnowsky

**Comment by alexey-tschudnowsky** [comment]
danke @timorosenblatt , ich kann den Fehler reproduzieren. Den ersten Erkenntnissen nach wird er durch ein (höchstwahrscheinlich unbeabsichtigtes aber trotzdem fehlerhaftes) Verhalten im zugrundeliegenden HL7 Java Validator [verursacht](https://github.com/hapifhir/org.hl7.fhir.core/blame/4de39a71da5b4ffe9f987c5d5ebcdb5950e216bd/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/elementmodel/Element.java#L408). Wir prüfen nun verfügbare Behandlungsoptionen für den Fehler.

**Comment by timorosenblatt** [comment]
Danke. Teilweise sind recht teure Rezepte betroffen.
Eine schnelle Lösung ist demnach extrem wichtig.

**Comment by alexey-tschudnowsky** [comment]
Das Problem wurde in dem [BugFix-Release 2.6.2](https://github.com/gematik/app-referencevalidator/releases/tag/2.6.2) behoben.

**Comment by ITKOE** [comment]
@timorosenblatt Danke für das Hinzufügen der Testdatei
@alexey-tschudnowsky Danke, dass Sie das Problem behoben haben
Artur
