### ISSUE TITLE
Ausgabe der Gültigkeitsprüfung mit gültigem Intervall

### ISSUE THREAD

**Issue by bneidhold** [gematik/app-referencevalidator#5]
IST: 
Profile https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Bundle|1.1.0 is invalid for the creation date of the resource (2023-05-30)

SOLL:
Profile https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Bundle|1.1.0 is invalid for the creation date of the resource (2023-05-30); only valid between 2023-07-01 and 3000-01-01

**Comment by alexey-tschudnowsky** [comment]
added in [Release 1.0.0](https://github.com/gematik/app-referencevalidator/releases/tag/1.0.0)
