### ISSUE TITLE
[Feature Request] Validierungsergebnis als OperationOutcome

### ISSUE THREAD

**Issue by lhns** [gematik/app-referencevalidator#6]
Hallo zusammen! Aktuell bekommt man nach einer Validierung ein `ValidationResult` zurück und kann mit `getValidationMessages` auf die einzelnen Message Objekte zugreifen. Es ist außerdem `toString()` implementiert um einen menschenlesbaren Text zu erzeugen. Dies wird auch in dem CLI Modul genutzt um die Ausgabe zu erzeugen.

Bei den meisten FHIR-Validator Implementierungen erhält man eine `OperationOutcome` Resource als XML die man dann in der weiterführenden Verarbeitung wieder maschinell auswerten kann. Bei BITMARCK sind aktuell alle nachgelagerten Prozesse um dieses OperationOutcome herum aufgebaut. Schön wäre eine Helper Methode mit der man aus dem ValidationResult ein OperationOutcome erzeugen kann. Außerdem wäre es sicherlich hilfreich wenn auch das CLI Modul eine Option bietet mit der man ein OperationOutcome erzeugen kann da man sich für das CLI Modul auch scriptgesteuerte Batchverarbeitung vorstellen kann.

**Comment by DarthGizka** [comment]
`ValidationResult::toOperationOutcome` existiert & braucht einfach nur aufgerufen zu werden. :wink:

Bezüglich der Nützlichkeit eines optionalen CLI-Parameters stimme ich voll zu.

**Comment by DarthGizka** [comment]
P.S.: es kann sinnvoll sein, daß OperationOutcome um strukturierte Zusatzinformationen (i.e. Extensions) zu ergänzen, z.B. um die Angabe der Validator-Gesamtbewertung (akzeptiert/abgewiesen) oder Informationen zur Umstufung von Einzelergebnissen des Validators (Black-/Whitelisting) bzw. zur Kennzeichen von Meldungen, die aus Zusatzprüfungen stammen und nicht aus dem HAPI-Validator. Das hat sich beim Einsatz in den Rechenzentren der [ARZsoftware eG][0] bewährt. Für den DAV/ABDA-Validator [hatte ich das mal aufgeschrieben][1]:

[0]: https://www.arz.software/
[1]: https://github.com/DAV-ABDA/eRezept-Referenzvalidator/issues/27

---

# Erweiterungen der Struktur OperationOutcome für den Referenzvalidator

Um das Prüfergebnis maschinell verarbeitbar zur Verfügung stellen zu können, ist es notwendig, einige Erweiterungen für Struktur [OperationOutcome][OO] zu definieren.

Diese Erweiterungen gliedern sich wie folgt:
* Erweiterungsfeld für die Angabe des Gesamturteils des Validators
* Erweiterungsfeld zur Kennzeichnung von Meldungen, die aus Zusatzprüfungen resultieren
* Zusatzinformationen zur Änderung der Einstufung von Meldungen aufgrund von Black- bzw. Whitelisting

## RV_EX_OperationOutcome_Gesamtbewertung

Das Gesamtergebnis der Validierung wird direkt in der Struktur OperationOutcome als Erweiterungsfeld kodiert. Es gibt nur zwei mögliche Werte: 'akzeptiert' und 'fehlerhaft'.

```xml
<OperationOutcome xmlns="http://hl7.org/fhir">
    <extension url="https://rz009.de/StructureDefinition/RV-EX-OperationOutcome-Gesamtbewertung">
        <valueCode value="akzeptiert"/>
    </extension>
    <issue>
        <severity value="information"/>
        <code value="informational"/>
        <diagnostics value="No issues detected during validation"/>
    </issue>
</OperationOutcome>
```

Diese Erweiterung wird nur dann kodiert, wenn der Validator tatsächlich zu einem Ergebnis gekommen ist. Steigt der Validator vorher aus - z.B. aufgrund einer Exception - dann fehlt die Erweiterung. Stattdessen enthält das Feld `diagnostics` die Meldung der Exception und `location` enthält den vollständigen Klassennamen; `severity` ist `fatal` und `code` ist `processing`.

## RV_EX_OperationOutcome_Pruefregel

Das Validierungsergebnis kann außer Meldungen aus dem eigentlichen FHIR-Validierungsvorgang auch Meldungen enthalten, die aus zusätzlichen Prüfungen resultieren. Diese Meldungen werden mit dem symbolischen Namen der jeweiligen Zusatzprüfung gekennzeichnet, um eine direkte Zuordnung zur jeweiligen Prüfdefinition zu ermöglichen und um diese zusätzlichen Meldungen von denen des eigentlichen HAPI-Validators unterscheiden zu können.
                             
```xml
<OperationOutcome xmlns="http://hl7.org/fhir">
    <issue>
        <extension url="https://rz009.de/StructureDefinition/RV-EX-OperationOutcome-Pruefregel">
            <valueString value="KEINE_RELATIVEN_PSEUDOREFERENZEN_FUER_UUID"/>
        </extension>
        <severity value="error"/>
        <code value="processing"/>
        <diagnostics value="relative Pseudoreferenzen vom Typ Ressourcename + '/' + UUID sind nicht zulaessig"/>
    </issue>
</OperationOutcome>
```           

## RV_EX_OperationOutcome_Umstufung

Diese Erweiterung gibt den symbolischen Namen einer Regel zum Black- oder Whitelisting an, die den Schweregrad der betreffenden Meldung herauf- oder heruntergestuft hat.
             
```xml
<OperationOutcome xmlns="http://hl7.org/fhir">
    <issue>
        <extension url="https://rz009.de/StructureDefinition/RV-EX-OperationOutcome-Umstufung">
            <extension url="Umstufungsgrund">
                <valueString value="UNBEKANNTE_ERWEITERUNG"/>
            </extension>
            <extension url="Originalwert">
                <valueCode value="information"/>
            </extension>
        </extension>
        <severity value="error"/>
        <code value="processing"/>
        <diagnostics value="Unknown extension 'https://foo/bar'"/>
    </issue>
</OperationOutcome>
```
                 
Anmerkung: die als Beispiel angegebenen Umstufung entspricht dem Verhalten des Standard-HAPI-Validators bei Angabe des Schalters `-strictExtensions`.

**Comment by alexey-tschudnowsky** [comment]
Hallo @DarthGizka ,

danke für die Ergänzungen. Was sind eigentlich die Use Cases für die Aufnahme der folgenden Informationen in die OperationOutcome (bzw. ValidationResult)?

> - Erweiterungsfeld zur Kennzeichnung von Meldungen, die aus Zusatzprüfungen resultieren
> - Zusatzinformationen zur Änderung der Einstufung von Meldungen aufgrund von Black- bzw. Whitelisting
> 

Zusatzprüfungen erhalten derzeit eine eigene issue.MessageId (fangen alle mit REFV_an...) Zusatzinformationen zur Änderung der Einstufung von Meldungen finden sich derzeit in den Protokollen des Referenzvalidators.

**Comment by lhns** [comment]
> `ValidationResult::toOperationOutcome` existiert & braucht einfach nur aufgerufen zu werden. 😉
> 
> Bezüglich der Nützlichkeit eines optionalen CLI-Parameters stimme ich voll zu.

Ah sehr hilfreich, vielen Dank! Ich habe es erst nicht gefunden weil hier `ca.uhn.fhir.validation.ValidationResult` gemeint ist, ich aber ein `de.gematik.refv.commons.validation.ValidationResult` zurückbekomme. Um eine Umwandlung vorzunehmen brauche ich einen FhirContext. An den komme ich über die Library wahrscheinlich nicht so einfach und muss ihn selber erstellen oder?

**Comment by alexey-tschudnowsky** [comment]
> > `ValidationResult::toOperationOutcome` existiert & braucht einfach nur aufgerufen zu werden. 😉
> > Bezüglich der Nützlichkeit eines optionalen CLI-Parameters stimme ich voll zu.
> 
> Ah sehr hilfreich, vielen Dank! Ich habe es erst nicht gefunden weil hier `ca.uhn.fhir.validation.ValidationResult` gemeint ist, ich aber ein `de.gematik.refv.commons.validation.ValidationResult` zurückbekomme. Um eine Umwandlung vorzunehmen brauche ich einen FhirContext. An den komme ich über die Library wahrscheinlich nicht so einfach und muss ihn selber erstellen oder?

in dem de.gematik.refv.commons.validation.ValidationResult gibt es die Methode (noch) nicht. Der Validator exponiert den internen FhirContext mit Absicht nicht, damit dieser nicht (unbeabsichtigt) verändert wird und somit das Verhalten vom Validator beeinflusst wird. Ggf. lässt sich die Konvertierung mit einem neu erzeugten FhirContext auch erreichen (ohne Gewähr!):

`ValidationResult result = erpModule.validateFile("src/test/resources/SimpleMedicationRequest.xml", options);
FhirContext theCtx = FhirContext.forR4();
ca.uhn.fhir.validation.ValidationResult hapiValidationResult  = new ca.uhn.fhir.validation.ValidationResult(theCtx, 
result.getValidationMessages().stream().collect(Collectors.toList()));
System.out.println(theCtx.newXmlParser().encodeResourceToString(hapiValidationResult.toOperationOutcome()));`

**Comment by lhns** [comment]
> > > `ValidationResult::toOperationOutcome` existiert & braucht einfach nur aufgerufen zu werden. 😉
> > > Bezüglich der Nützlichkeit eines optionalen CLI-Parameters stimme ich voll zu.
> > 
> > 
> > Ah sehr hilfreich, vielen Dank! Ich habe es erst nicht gefunden weil hier `ca.uhn.fhir.validation.ValidationResult` gemeint ist, ich aber ein `de.gematik.refv.commons.validation.ValidationResult` zurückbekomme. Um eine Umwandlung vorzunehmen brauche ich einen FhirContext. An den komme ich über die Library wahrscheinlich nicht so einfach und muss ihn selber erstellen oder?
> 
> in dem de.gematik.refv.commons.validation.ValidationResult gibt es die Methode (noch) nicht. Der Validator exponiert den internen FhirContext mit Absicht nicht, damit dieser nicht (unbeabsichtigt) verändert wird und somit das Verhalten vom Validator beeinflusst wird. Ggf. lässt sich die Konvertierung mit einem neu erzeugten FhirContext auch erreichen (ohne Gewähr!):
> 
> `ValidationResult result = erpModule.validateFile("src/test/resources/SimpleMedicationRequest.xml", options); FhirContext theCtx = FhirContext.forR4(); ca.uhn.fhir.validation.ValidationResult hapiValidationResult = new ca.uhn.fhir.validation.ValidationResult(theCtx, result.getValidationMessages().stream().collect(Collectors.toList())); System.out.println(theCtx.newXmlParser().encodeResourceToString(hapiValidationResult.toOperationOutcome()));`

Genau so habe ich es jetzt auch gelöst. Vielen Dank für die Rückmeldung!

**Comment by DarthGizka** [comment]
Sorry, es wäre mir nie in den Sinn gekommen, daß eine Klasse unter `de.gematik`
(a) `ValidationResult` heißt anstelle von `Validierungsergebnis`
(b) einen Namen hat, der eine notwendigerweise im Umlauf befindliche Klasse von `ca.uhn` versteckt/überdeckt
...

Mea culpa.

In dieser Situation wäre es natürlich angezeigt, eine entsprechende Methode zum Generieren des OperationOutcome vorzusehen, mit Injektion eventueller Extensions für Gesamtbewertung usw. 

Was die Extensions angeht: ich hatte das extra hier als P.S. gepostet und nicht als separates Issue an die große Glocke gehängt, weil der Text auf den DAV/ABDA-Validator und die damalige Situation gemünzt ist. Ich wollte die Idee wieder nur unters Volk streuen, damit interessierte Geister sie bei Gefallen in ihr Arsenal einreihen können. :wink:

Das Kennzeichnen von umgestuften Validatormeldungen (Black-/Whitelisting) ist insbesondere dann hilfreich, wenn man die Ergebnisse verschiedener Validatoren vergleicht. Ansonsten könnte man sich wundern, warum ein und dieselbe Meldung bei einem Validator als Warnung oder Info daherkommt und bei einem anderen als Fehler; in solchen Fällen würde man eher unterschiedliche Konfiguration als Ursache vermuten und nicht zielgerichtete Aktivität. 

Eine gesonderte Kennzeichnung von hinzugekommenen - also nicht aus dem HAPI-Validator stammenden - Meldungen ist in der Tat überflüssig, wenn diese anhand des Message-Id-Präfix zweifelsfrei erkannt werden können.

**Comment by alexey-tschudnowsky** [comment]
Hallo @lhns ,
in der frisch veröffentlichten [Version 2.2.0 vom Referenzvalidator](https://github.com/gematik/app-referencevalidator/releases/tag/2.2.0) ist der Kommandozeilenparameter `--output OUTPUT_FILE_NAME` enthalten, mit dem das Schreiben des Validierungsergebnisses in eine Ausgabedatei nun möglich ist. Geschrieben wird eine OperationOutcome (siehe [Strukturdefinitionen](https://github.com/gematik/app-referencevalidator/tree/main/docs/profiles/fsh/fsh-generated/resources)).
Um eine OperationOutcome im Code zu erzeugen kann die Klasse [ValidationResultToOperationOutcomeConverter](https://github.com/gematik/app-referencevalidator/blob/main/commons/src/main/java/de/gematik/refv/commons/validation/ValidationResultToOperationOutcomeConverter.java) verwendet werden. Ich hoffe, damit lassen sich Eure Szenarien effizienter implementieren.

**Comment by lhns** [comment]
Ich habe die neue Klasse gerade getestet und es funktioniert einwandfrei. Vielen Dank!
