### ISSUE TITLE
Validierung der Adresszeile

### ISSUE THREAD

**Issue by timorosenblatt** [gematik/app-referencevalidator#8]
Die bisherigen Validatoren liefern Fehler oder Warnungen bei diesem Konstrukt:
Am Ende der Strasse ist ein Leerzeichen, im Line value sind zwei Leerzeichen zwischen Strasse und Hausnummer.
Firely liefert einen Fehler. Der ABDA Referenzvalidator eine Warnung, die auf das Leerzeichen hinweist.
Warnungen werden aber auch abgelehnt.

Dieser Validator akzeptiert es so, wie es ist.
Ist das so gewollt?

          <line value="Alexander-König-Str.  20">
            <extension url="http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName">
              <valueString value="Alexander-König-Str. ">
              </valueString>
            </extension>
            <extension url="http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber">
              <valueString value="20">
              </valueString>
            </extension>
          </line>

**Comment by alexey-tschudnowsky** [comment]
Hallo @timorosenblatt , 

beim ABDA Referenzvalidator werden die Warnungen durchaus akzeptiert: https://github.com/DAV-ABDA/eRezept-Referenzvalidator/blob/fd22441e64005ad8893a646d780537bb6b13ca6b/core/src/main/java/de/abda/fhir/validator/core/Validator.java#L100 und führen NICHT zu einem invaliden Ergebnis. 

Ist Ihnen eine Anforderung oder Regel im Kontext der E-Rezept-Verarbeitung bekannt, die Leerzeichen am Anfang oder Ende eines Strings verbieten würde? 

Mit freundlichen Grüßen
Alexey Tschudnowsky

**Comment by timorosenblatt** [comment]
Ich weiß, dass es in der Vergangenheit öfter Probleme mit den Leerzeichen am Ende gab.
Eine genaue Stelle ist mir jetzt nicht bekannt.

Uns ist das o.g. Problem beim Firely aufgefallen, weil wir diese Konstellation in der PU abgelehnt haben.
Aber wenn das zukünftig so zu akzeptieren ist, dann müssen wir da etwas anpassen.

**Comment by DarthGizka** [comment]
FWIW: der Standard adressiert das Problem mit führendem und nachfolgendem Whitespace bei der Definition der XML-Kodierung von FHIR (aber *nicht* für JSON):

[2.6.1 XML Representation of Resources][2.6.1] (R4)
```
• Implementers SHOULD trim leading and trailing whitespace before writing and SHOULD trim leading and trailing whitespace when reading attribute values (for XML schema conformance)
```

Es handelt sich um eine Kann-Bestimmung ohne Ausblick auf Überführung in eine Pflichtregel. Daher ist sie schlimmer als die Abwesenheit einer Regelung: sie kann für niemanden irgendetwas garantieren und produziert im wesentlichen nur Ärger. 

Bezüglich mehrfacher konsekutiver Whitespace-Zeichen im Innern von Werten gibt es nur eine sanfte, indirekte Andeutung, daß diese nicht wirklich als Teil einer FHIR-Ressource betrachtet werden. Diese Andeutung besteht aus einer Kanonisierungsregel, welche in äquivalenter Form sowohl für XML als auch für JSON definiert ist:
```
No whitespace other than single spaces in attribute values and in the XHTML in the [Narrative](https://hl7.org/fhir/R4/narrative.html)
```

Theoretisch könnten Profilautoren das Problem über Regex-Einschränkungen angehen (der GKV hatte wohl sowas mal angedeutet). Das würde allerdings die Profile gewaltig aufblähen und nur noch mehr Fehlerpotential stiften. Die einzige realistische Möglichkeit ist Festlegung einer verbindlichen übergeordneten Regel durch die Technische Kommission - analog zur Vorschrift, daß FHIR bei E-Rezepten nur als XML in UTF-8 ohne BOM daherkommen soll - in Verbindung mit Durchsetzung der Regel über den Referenzvalidator. 

Redundanter umgebender Whitespace ist dabei einfacher zu handhaben als nicht-kanonischer Whitespace im Innern, weil der HAPI-Validator für ersteres bereits eine Warnung generiert (die man nur hochstufen müßte zu einem Fehler). Für nicht-kanonischen Whitespace im Inneren müßte der Validator mit einer passenden Regex durch alle Elemente der zu validierenden Strukturen durchwackeln; das ist zwar nicht trivial, aber es ist auch keine Raketenwissenschaft. Am Ende würde für alle Beteiligten größere Sicherheit herausspringen.

P.S.: bei [ERPFIND-545](https://service.gematik.de/projects/ERPFIND/issues/ERPFIND-545) (nur aus Whitespace bestehende Textelemente) geht es zwar auch um Whitespace, aber dort ist die zugrundeliegende Regel nicht optional:
```
• Attributes cannot be empty. Either they are absent, or they are present with at least one character of non-whitespace content
```
Das Problem ist dort, daß die Verletzung dieser Pflichtregel bei HAPI nur eine Warnung ergibt, obwohl standardkonforme FHIR-Prozessoren die Verarbeitung schlicht verweigern können (e.g. Firely ohne ausdrückliche Option für permissives Parsen). IOW, die Sache gehört ebenfalls zum Problemkreis 'Umgang mit Whitespace', und sie kann ebenfalls durch Umstufen einer Warnung behandelt werden. Sie ist aber von ihrer Natur her (Pflicht- statt Kann-Regel) etwas anders gelagert.

[2.6.1]: https://hl7.org/fhir/R4/xml.html#2.6.1

**Comment by alexey-tschudnowsky** [comment]
Bis auf Weiteres sollen die führenden und abschließenden Leerzeichen zu **keiner** Ablehnung führen. 

Das Thema wurde aber vom E-Rezept-Team der gematik und den eingebundenen Sektoren aufgenommen und wird neu bewertet. Sollte sich die Regel in Zukunft ändern, wird deren Inkrafttreten mit ausreichendem Vorlauf angekündigt, da nicht nur der Fachdienst sondern auch die erzeugenden Systeme ggf. alle angepasst werden müssten
